### ISSUE TITLE
 Feature Request: Auto update in addition to update check for dshidmini

### ISSUE THREAD

**Issue by successtheman** [nefarius/DsHidMini#19]
Currently I find myself manually copying the new exe over every time there is a new version etc... I think implementing something similar to scptoolkit's old update functionality where it did the work for you and replaced the old exe with the new one would be nice. Even something similar to ds4windows update functionality would be very helpful in my opinion.

**Comment by nefarius** [comment]
I will do that once out of beta; I can not yet guarantee non-API-breaking changes between driver and UI so I'd need to also implement a strict driver version check and update that too.

**Comment by nefarius** [comment]
News on this: since I have renewed my Advanced Installer subscription we can make an auto-updater a reality 🥳

**Comment by nefarius** [comment]
Once we have a setup I'll use [vicius](https://github.com/nefarius/vicius) for the updating part as soon as it has matured.

**Comment by nefarius** [comment]
No longer relevant.

**Comment by nefarius** [comment]
Consolidated in #211.
