### ISSUE TITLE
Create small driver installer

### ISSUE THREAD

**Issue by nefarius** [nefarius/DsHidMini#211]
I've got enough snippets and libraries now to basically offer a small, simple .NET-based installer, should further reduce the possibility of installation issues either due to missing a step or something unaccounted for, like UAC being turned off.

Related to #19 and #47

**Comment by sitiom** [comment]
I have added DsHidMini to Scoop for the meantime (https://github.com/ScoopInstaller/Nonportable/pull/22).

**Comment by nefarius** [comment]
Progress! Even managed to add a selection-based BthPS3 download-and-install option 🥳 

![image](https://user-images.githubusercontent.com/286631/187186244-ea82081b-144e-4df8-a9d8-54bbca5b8511.png)

**Comment by gosseux** [comment]
will this installer appear in the add/remove program list for easy uninstall as well ?

**Comment by nefarius** [comment]
> will this installer appear in the add/remove program list for easy uninstall as well ?

Well ofc. 😉

**Comment by nefarius** [comment]
![image](https://github.com/nefarius/DsHidMini/assets/286631/e2811d0b-cf71-49fa-943b-809edfe507e3)

![image](https://github.com/nefarius/DsHidMini/assets/286631/aec0ef38-10e5-40e2-a408-46f2af5163a3)
