### ISSUE TITLE
High CPU of Windows Driver Foundation after a while in SXS mode

### ISSUE THREAD

**Issue by FuJa0815** [nefarius/DsHidMini#263]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://vigem.org/Community-Support/
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am using DsHidMini for a Dualshock 3 controller. After a while the CPU usage of `Windows Driver Foundation - User-mode Driver Framework Host Process` starts rising and rising. This leads to PCSX2 getting slower and slower. After reconnecting the controller the CPU usage is down again and everything runs smoothly. I have already reinstalled the drivers, did not work.

### Screenshots

![image](https://user-images.githubusercontent.com/30809803/201527720-4e6be438-1b50-407f-8624-b894e7fda43e.png)
![image](https://user-images.githubusercontent.com/30809803/201527993-b7bddbe2-4447-4569-a0c9-777673cb8ae4.png)

### Machine info

**CPU-Architecture:** x64
**Windows version:** Windows 10.0.19043 Build 19043
**Software/driver version(s):** 2.2.282.0

### Any other helpful information
[DSHMC20221113.txt](https://github.com/ViGEm/DsHidMini/files/9997467/DSHMC20221113.txt)

I am aware that reproducing this error might be difficult. I also don't have any "proof" that DsHidMini is 100% at fault here, but reconnecting the controller fixes this issue again for a while, therefore it seems obvious to me.

**Comment by nefarius** [comment]
Are you using the XI proxy DLL?

**Comment by mrpenguinb** [comment]
I have the same issue, after a while the WDF process got to 10 or more percent CPU usage. I'm using the x64 XInput .dll for PCSX2.

**Comment by englebert3rd** [comment]
I'm getting the same issue using the proxy DLL.

**Comment by nefarius** [comment]
To those affected feel free to [test it with the complete overhaul of the DLL](https://docs.nefarius.at/projects/DsHidMini/SCP-XInput-Bridge/#latest-downloads), it works with the old driver just fine, no need for any other upgrades.

**Comment by MoaMission** [comment]
I can confirm that the issue seems to be resolved. I haven't noticed a VRAM or CPU ramp-up after playing for ten minutes like before.

Thanks so much for addressing this!

**Comment by nefarius** [comment]
Pretty much a complete rewrite, yeah. More sophisticated and thought through. You can see all the work in the finished pull requests and the commit history.

**Comment by NonOriginalName** [comment]
I'm having a high CPU usage spike after like half an hour or so of using my ps3 controller with DsHidmini 3.0 when playing Twilight Princess Dusklight port. Using the reworked DLL doesn't work as well.

**Comment by dotur911** [comment]
I can can confirm ,i have that problem too.

**Comment by MoaMission** [comment]
I remember this post from May. I have a suspicion it's because that very particular project uses an outdated emulator / outdated methods as a baseline for playing Twilight Princess. You should really take it up with the devs of that 'port' program...not here.

...but that's just my take. I'll let nefarius respond and look into it.

**Comment by nefarius** [comment]
OK so since it is apparently too hard to grasp that this topic is done and had nothing to do with this project I'll lock this issue.
