### ISSUE TITLE
DsHidMini v3 not loading device specific settings when controller is connected via BT

### ISSUE THREAD

**Issue by Kanuan** [nefarius/DsHidMini#310]
This is the configuration file I'm using: [DsHidMini.txt](https://github.com/nefarius/DsHidMini/files/12328893/DsHidMini.txt) (changed from .json to .txt to upload the file here on github)

This is the tracing results when connecting the controller via USB:

![image](https://github.com/nefarius/DsHidMini/assets/24910442/50ba0236-6dd6-4876-88d9-1c53100a1b61)

This is the result when connecting via BT (note that the "device specific" line is missing):

![image](https://github.com/nefarius/DsHidMini/assets/24910442/544aa060-cd83-440d-a66e-e78051071ec2)

----------- 

I'm pretty sure I wasn't running on this problem before updating the BthPS3 version (currently I'm using version 2.8.320.0). Will test if it's actually a BthPS3 issue somehow

**Comment by Kanuan** [comment]
> I'm pretty sure I wasn't running on this problem before updating the BthPS3 version (currently I'm using version 2.8.320.0). Will test if it's actually a BthPS3 issue somehow

Yeah, no,  the same issue happens under BthPS3 v2.6.127.0. I think I just didn't notice this issue before because I was using global settings the majority of time

**Comment by nefarius** [comment]
Not sure I ever tested it wireless since it was introduced, so can totally be the case it's overlooked, will check it out.

**Comment by Kanuan** [comment]
In `configuration.c`, the `ConfigLoadForDevice` method gets the string that represents the device MAC address from the `Context->DeviceAddressString` field. The issue is that this field is not set when the device is connected via BT.

I've added a tracing message for it to show this field value if it fails to load the settings and it returns blank when via BT:
![image](https://github.com/nefarius/DsHidMini/assets/24910442/1c000248-307a-4570-a27b-82133635e812)
![image](https://github.com/nefarius/DsHidMini/assets/24910442/0e855647-fcb5-42bb-9e3c-dfa0aaa3ff00)

From what I've looked around, The device's `DeviceAddressString` field is only set in the `DsUdb_PrepareHardware` method of the `DsUsb.c` file, but this method is only called if the device is connected via USB, therefore the `DeviceAddressString` field is never set via BT:
![image](https://github.com/nefarius/DsHidMini/assets/24910442/8390f43d-72ce-459c-8177-54098e4024b8)
![image](https://github.com/nefarius/DsHidMini/assets/24910442/b72805f3-2de1-4677-82af-ae9ba3dcd601)

I tried to set `DeviceAddressString` in the `DsDevice_ReadProperties` method of the `device.c` file immediately after it sets the `DeviceAddress` field. This works in the sense that the field is correctly set, but for some reason putting this piece of code here causes the driver to get stuck immediately after it:
![image](https://github.com/nefarius/DsHidMini/assets/24910442/444ec77d-2fd5-49ff-adf4-02b6ff7cf0b8)
![image](https://github.com/nefarius/DsHidMini/assets/24910442/1787be55-bcf9-475e-a0d3-eaeeeb55b21a)

**Comment by Kanuan** [comment]
From the traceview log, the driver hangs if  `DeviceAddressString` is set before invoking the `DsDevice_RegisterBthDisconnectListener` method. Setting the `DeviceAddressString` field AFTER both listerner-related methods are invoked fix the hanging and the code works as expected, allowing the driver to properly load device-specific configurations.

I'm really curious to why the driver hangs if the `DeviceAddressString` field is set before the listener-related methods are invoked, nothing in them seems to make use of it, but regardless, this got the "works on my machine" seal of approval. Will prepare a PR for the fix.

**Comment by Kanuan** [comment]
From the traceview log, the driver hangs if  `DeviceAddressString` is set before invoking the `DsDevice_RegisterBthDisconnectListener` method. Setting the `DeviceAddressString` field AFTER both listerner-related methods are invoked fix the hanging and the code works as expected, allowing the driver to properly load device-specific configurations.

![image](https://github.com/nefarius/DsHidMini/assets/24910442/14239c5a-e6be-4bac-bdcf-50e24385d62e)


I'm really curious to why the driver hangs if the `DeviceAddressString` field is set before the listener-related methods are invoked, nothing in them seems to make use of it, but regardless, this got the "works on my machine" seal of approval. Will prepare a PR for the fix.

**Comment by nefarius** [comment]
If the tracing just stops and the driver responding, it means it crashed. Look in the event viewer for Critical or Error events from the user-mode driver reflector service, I bet you find one or more crash logs.

**Comment by nefarius** [comment]
Should look similar to #333

**Comment by Kanuan** [comment]
![image](https://github.com/nefarius/DsHidMini/assets/24910442/04546656-fca2-4836-a741-f509bf5f7e07)

**Comment by nefarius** [comment]
Yeah that's why I thought, we're probably reading or writing invalid/uninitialized memory somewhere during this exact sequence or in parallel and it goes poof. WinDbg session or code review could uncover why exactly.

**Comment by nefarius** [comment]
Once you make a PR and I see the diff, maybe something obvious jumps out.
