### ISSUE TITLE
Dualshock 3 has extreme latency drops when a Dualsense is connected

### ISSUE THREAD

**Issue by babbymode** [nefarius/DsHidMini#323]
### Bug description

Massive latency spiking when a Dualsense controller is also connected via BT connection.

### Steps to reproduce

Connect Dualshock 3 via bluetooth
Connect Dualsense via bluetooth
Dualshock 3 latency spikes hard
Dualsense is unaffected (~1ms)
Turn off Dualsense
DS3 latency drops to ~4 ms from 250-5000ms+
### Screenshots
BthPS3 Trace log is 99.9% this, no errors, 1 warning on a disconnect at the beginning probably when i was switching from USB to BT:
![TraceView_h8NzKupuMV](https://github.com/nefarius/DsHidMini/assets/36177514/bb4e4f35-8756-41da-8103-be8ea27e647f)

### Machine info

**Windows version:** Windows 10 x64, Bluetooth Driver: Intel® Wi-Fi 6E AX210 160MHz
**Software/driver version(s):** DSHidMini 2.2.282.0, BthPS3 2.8.320

### Any other helpful information

Hard to say, I have tried everything from entirely reinstalling dshidmini via the guide, messing with output rate control and polling rates, nothing seems to correlate to it positively. Other controllers also appear to work fine, but specifically when my Dualsense is connected, regardless of the method (DS3 on SXS thru steam, DS4win, xinput, etc). I wish I had more to tell but the next best thing I have is the log file

**Comment by nefarius** [comment]
This simply means your setup does not have enough bandwidth capacity to support both these devices in parallel, nothing the driver software can do for you there.
