### ISSUE TITLE
igfilter and nssmkig.sys missing when building with Visual Studio

### ISSUE THREAD

**Issue by habibendris** [nefarius/DsHidMini#327]
I can't be able to find igfilter and nssmkig.sys when building with Visual Studio.

**Comment by nefarius** [comment]
Because those are not FOSS components, I provide the binaries when making a release.

**Comment by habibendris** [comment]
Can i build those myself

**Comment by nefarius** [comment]
As I said, the sources are not publicly available, so no.

**Comment by habibendris** [comment]
are those mandatory if i build it myself

**Comment by nefarius** [comment]
For building, no. For operation, yes.
