### ISSUE TITLE
[Windows 10] Controller experiences device timeout (Code 10)

### ISSUE THREAD

**Issue by AFriendlyIrin** [nefarius/DsHidMini#332]
**ETA:** Literally as soon as I posted this, Nefarius HID Devices reappeared. Investigating the controller gets the following error message:

> This device cannot start. (Code 10)
{Device Timeout}
The specified I/O operation on %hs was not completed before the time-out period expired.

### Bug description

Everything was working perfectly, but all of a sudden my controller can no longer be detected by Device Manager or DSHMC, whether by USB or wireless. The Nefarius HID Devices category in Device Manager ~~has completely disappeared~~ seems erratic and displays the controller with a warning sign; investigating produces the above error. I can still find the drivers with Driver Store Explorer, and attempting to remove dshidmini.inf produces an error stating that it is still in use. Windows can recognize the controller in the device list, but displays it with a "Driver Error" message. I attempted to delete and reinstall the drivers as well as restart my computer several times, but the problem persists.

The Bluetooth drivers are also installed.

The controller LED is a solid light at position 4. Plugging/unplugging through USB doesn't reset this.

### Steps to reproduce

I am not certain how to reproduce the issue, as I can't get DsHidMini working again to test it.

### Screenshots

![Capture](https://github.com/nefarius/DsHidMini/assets/77584000/a225f8ac-f853-4f4f-a4db-472536dcae2e)
![Capture](https://github.com/nefarius/DsHidMini/assets/77584000/e134ac4c-a11d-4829-9fa9-4ae1b01936b1)
![Capture](https://github.com/nefarius/DsHidMini/assets/77584000/a072c178-df90-4bc1-91ca-6392e9b6e8b9)

### Machine info

**CPU-Architecture:** x64
**Windows version:** Windows 10.0.19045
**Software/driver version(s):** 2.2.282

### Additional information
My controller is a legitimate PS3 Sixaxis controller.

I had SCP Toolkit installed, but removed it with Legacinator. I don't have any of the other drivers listed as compatibility issues.

**Comment by nefarius** [comment]
What is the error code and message of the device with the exclamation mark?

**Comment by nefarius** [comment]
This error [is covered in the FAQ](https://docs.nefarius.at/projects/DsHidMini/FAQ/#how-to-fix-device-timeout).

**Comment by AFriendlyIrin** [comment]
It was working just a few minutes earlier, though, and I've been using this controller for years without issue. How did the hardware suddenly break?

**Comment by nefarius** [comment]
> It was working just a few minutes earlier, though, and I've been using this controller for years without issue. How did the hardware suddenly break?

IDK, I never could reproduce this myself, I have no solution for you.

**Comment by AFriendlyIrin** [comment]
I switched back to ScpToolkit and it works fine again.

You might want to revise that bit in your FAQ about how DsHidMini is so much better than your old decrepit version.

**Comment by nefarius** [comment]
> I switched back to ScpToolkit and it works fine again, so it's definitely a software problem.
> 
> You might want to revise that bit in your FAQ about how DsHidMini is so much better than your old decrepit version.

Or, how about, people start contributing fixes and solutions instead of waiting for me to do all the work? 😉

**Comment by nefarius** [comment]
> You might want to revise that bit in your FAQ about how DsHidMini is so much better than your old decrepit version.

As I said; I do not have any issues. Come up with the solution, the code is open, expecting a fix next week! It's easy, it's just software, after all!

**Comment by nefarius** [comment]
> I switched back to ScpToolkit and it works fine again

NVM then, glad to see it resolved! ♥
